version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /app.py
    destination: home/ec2-user/football-analytics-app/
  - source: /assets
    destination: home/ec2-user/football-analytics-app/assets/
  - source: /requirements.txt
    destination: home/ec2-user/football-analytics-app/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 100
      runas: root
    - location: scripts/start_server
      timeout: 100
      runas: root
    - location: scripts/run_all.py
      timeout: 100
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 100
      runas: root

